###
# MINIO
##

services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    volumes:
      - ./minio-data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_SERVER_URL: ${MINIO_SERVER_URL}
    command: server /data --console-address ":9090"
  nginx:
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8081:81"
      - "4443:443"
    environment:
      - TZ=America/Sao_Paulo
      - DB_SQLITE_FILE=/data/database.sqlite
      - DISABLE_IPV6=true
    volumes:
      - ./nginx-data:/data
      - ./nginx-letsencrypt:/etc/letsencrypt
# networks:
#   easypanel_network:
#     external: true
